### ISSUE TITLE
Non-increasing argument indices causes data corruption in output

### ISSUE THREAD

**Issue by kevsecurity** [cilium/tetragon#1043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I specified arguments to a kprobe out of order, e.g. index: 2, index: 1. The BPF code writes the argument data in strict increasing order, but the user space reads the argument data in specified order. This causes the data to be allocated to the incorrect arguments.

### Tetragon Version

master

### Kernel Version

5.15

### Kubernetes Version

N/A

### Anything else?

I had a partial fix but it failed to adequately consider arguments that are read on retprobes.
Essentially, the index in the argPrinters list can be set to the argument index instead of sequential index (which appears to not be used); the printers can then be ordered in increasing order by index before the argument data is read; this should be stored in a map against the index. Following, the original order of the printers can then be used to build the unix.Args in the specified order, by looking. up the printers indices in the new map.
This mostly works but more work is required around return arguments. I will pick this up when I have cycles.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mtardy** [comment]
Was this fixed with the recents changed @olsajiri (cc @kkourt also)?

**Comment by olsajiri** [comment]
I think so, @kevsecurity could you please retest with current code? thanks

**Comment by kevsecurity** [comment]
> I think so, [@kevsecurity](https://github.com/kevsecurity) could you please retest with current code? thanks

Yep, I'll test today.

**Comment by kevsecurity** [comment]
Yep, with this yaml:
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "tcp-set-state"
spec:
  kprobes:
  - call: "tcp_set_state"
    syscall: false
    args:
    - index: 1
      type: "int"
      label: "state"
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "State"
        values:
        - "TCP_SYN_RECV"
      - index: 1
        operator: "Equal"
        values:
        - 1
```

I get events like this:
```
{"process_kprobe":{"process":{"exec_id":"ZTMzOGRhYzRjNTQ1OjI2MDY4MDI4MDA2NDc4MjozODE1Mw==", "pid":38153, "uid":0, "cwd":"/root", "binary":"/usr/bin/nc", "arguments":"127.0.0.1 8899", "flags":"execve clone", "start_time":"2025-06-27T10:21:33.985935631Z", "auid":4294967295, "parent_exec_id":"ZTMzOGRhYzRjNTQ1OjEzMjI0MDAwMDAwMDo1MDU=", "refcnt":1, "tid":38153, "in_init_tree":false}, "parent":{"exec_id":"ZTMzOGRhYzRjNTQ1OjEzMjI0MDAwMDAwMDo1MDU=", "pid":505, "uid":0, "cwd":"/root", "binary":"/usr/bin/bash", "flags":"procFS auid", "start_time":"2025-06-24T09:59:05.945853219Z", "auid":4294967295, "parent_exec_id":"ZTMzOGRhYzRjNTQ1OjEzMjE3MDAwMDAwMDo1MDM=", "tid":505, "in_init_tree":false}, "function_name":"tcp_set_state", "args":[{"int_arg":1, "label":"state"}, {"sock_arg":{"family":"AF_INET", "type":"SOCK_STREAM", "protocol":"IPPROTO_TCP", "saddr":"127.0.0.1", "daddr":"127.0.0.1", "sport":8899, "dport":49308, "cookie":"18446633810749701888", "state":"TCP_SYN_RECV"}}], "action":"KPROBE_ACTION_POST", "policy_name":"tcp-set-state", "return_action":"KPROBE_ACTION_POST"}, "node_name":"e338dac4c545", "time":"2025-06-27T10:21:33.989515484Z"}
```

Which appear correct.
