### ISSUE TITLE
Add the "Prefix" operator for the "matchBinaries" selector

### ISSUE THREAD

**Issue by Vampouille** [cilium/tetragon#1278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I would like to forbid network usage for every binaries in a specific folder. For example, binaries in `~/bin-no-network/` should not be able to create socket. This can be done with the following TracingPolicy: 

```yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "connect"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
          - "/home/jacroute/bin-no-network/curl"
          - "/home/jacroute/bin-no-network/jq"
      matchActions:
      - action: Sigkill
```

But we need to list every binary in this folder and keep this list up-to-date.

### Describe the feature you would like

I can be nice to use the "Prefix" operator for this use-case but only "In" and "NotIn" operators are currently [implemented](https://github.com/cilium/tetragon/pull/686/files#diff-0b6c66cf370068fe2e441466d6124582732e8b67dd0daddccf72c7eb2bef16d4R994-R1000)

With this new feature, the TracingPolicy should look like : 

```yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "connect"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchBinaries:
      - operator: "Prefix"
        values:
          - "/home/jacroute/bin-no-network/"
      matchActions:
      - action: Sigkill
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
