### ISSUE TITLE
Add the "NotPrefix" and "NotPostfix" Operators to suitable Selector Types

### ISSUE THREAD

**Issue by BonySmoke** [cilium/tetragon#1310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

We would like to block all write requests to files under a particular directory with the exception of certain folders.
Following the existing [example](https://github.com/cilium/tetragon/blob/19fdc3a56629e5396477baa776c599d2bbc76299/examples/tracingpolicy/open_kill.yaml), we can kill all processes that try to write to any file under the `/home` folder using the `Prefix` operator:
```yaml
  kprobes:
...
  - call: "sys_write"
    syscall: true
    args:
    - index: 0
      type: "fd"
    - index: 1
      type: "char_buf"
      sizeArgIndex: 3
    - index: 2
      type: "size_t"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/home/"
      matchActions:
      - action: Sigkill
```
However, we have folders under `/home` where we still would like to allow write requests.

If I understand it correctly, currently, it's only possible to add exact files to exceptions using the `NotEqual` operator.
```yaml
...
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/home/"
      - index: 0
        operator: "NotEqual"
        values:
        - "/home/anotherfolder/file.txt"
      matchActions:
      - action: Sigkill
```
Unfortunately, we cannot predict what files/directories will be in the `/home/anotherfolder` folder.

### Describe the feature you would like

It would be great to add a `NotPrefix` and optionally `NotPostfix` operators to the suitable selector types to make filtering much more flexible.
Using the example above, we could end up with the following selector:
```yaml
...
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/home/"
      - index: 0
        operator: "NotPrefix"
        values:
        - "/home/anotherfolder/"
      matchActions:
      - action: Sigkill
```
And this would translate to `(filepath starts with "/home/" AND filepath NOT starts with "/home/anotherfolder/")`

### Describe your proposed solution

I saw this [commit](https://github.com/cilium/tetragon/commit/edcebe77b5f52cd601d007661d07c8bcbf622605) adding a negative filter. Maybe the implementation of this feature will be similar.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
