### ISSUE TITLE
sys_close kprobe inside a TracingPolicyNamespaced policy does not honor NoPost action

### ISSUE THREAD

**Issue by ashishkurmi** [cilium/tetragon#1341]
### What happened?

I'm currently using a TracingPolicyNamespaced policy to monitor file activities. I attempted to suppress events generated by sys_close using the 'NoPost' action, but it doesn't appear to be working.

```yaml
TracingPolicyNamespaced policy:
apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "sys-read-follow-prefix"
spec:
  kprobes:
    - call: "fd_install"
      syscall: false
      return: false
      args:
        - index: 0
          type: int
        - index: 1
          type: "file"
      selectors:
        - matchActions:
            - action: FollowFD
              argFd: 0
              argName: 1
    - call: "sys_close"
      syscall: true
      args:
        - index: 0
          type: "int"
      selectors:
        - matchActions:
            - action: UnfollowFD
              argFd: 0
              argName: 0
            - action: NoPost
    - call: "sys_read"
      syscall: true
      args:
        - index: 0
          type: "fd"
        - index: 1
          type: "char_buf"
          returnCopy: true
        - index: 2
          type: "size_t"
    - call: "sys_write"
      syscall: true
      args:
        - index: 0
          type: "fd"
        - index: 1
          type: "char_buf"
          sizeArgIndex: 3
        - index: 2
          type: "size_t"
```

Script to generate file events after deploying the above TracingPolicyNamespaced

```bash
#!/bin/bash

while true; do
    RANDOM_NAME=$(date +%s%N)
    echo "This is a test content for file $RANDOM_NAME" > "$RANDOM_NAME.txt"
    cat "$RANDOM_NAME.txt"
    rm -f "$RANDOM_NAME.txt"
    sleep 1
done
```

You can see :mailbox_closed: close events generated by Tetragon below:
```
kubectl logs -n kube-system -l app.kubernetes.io/name=tetragon -c export-stdout -f | tetra getevents -o compact

💥 exit    default/testpod /usr/bin/cat 1691554579712634240.txt 0 
📪 close   default/testpod /usr/bin/bash                                    
🚀 process default/testpod /usr/bin/rm -f 1691554579712634240.txt  
📬 open    default/testpod /usr/bin/rm /etc/ld.so.cache            
📪 close   default/testpod /usr/bin/rm                                      
📬 open    default/testpod /usr/bin/rm /usr/lib/x86_64-linux-gnu/libc.so.6 
📚 read    default/testpod /usr/bin/rm /usr/lib/x86_64-linux-gnu/libc.so.6 832 bytes 
📪 close   default/testpod /usr/bin/rm                                      
📪 close   default/testpod /usr/bin/rm                                      
📪 close   default/testpod /usr/bin/rm                                      
📪 close   default/testpod /usr/bin/rm                                      
💥 exit    default/testpod /usr/bin/rm -f 1691554579712634240.txt 0 
📪 close   default/testpod /usr/bin/bash                                    
🚀 process default/testpod /usr/bin/sleep 1                        
📬 open    default/testpod /usr/bin/sleep /etc/ld.so.cache         
📪 close   default/testpod /usr/bin/sleep                                   
📬 open    default/testpod /usr/bin/sleep /usr/lib/x86_64-linux-gnu/libc.so.6 
📚 read    default/testpod /usr/bin/sleep /usr/lib/x86_64-linux-gnu/libc.so.6 832 bytes 
📪 close   default/testpod /usr/bin/sleep
```

### Tetragon Version

0.10.0

### Kernel Version

Linux ip-10-0-51-149.us-west-2.compute.internal 5.10.184-175.731.amzn2.x86_64 https://github.com/cilium/tetragon/pull/1 SMP Tue Jun 27 21:48:55 UTC 2023 x86_64 Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.3-eks-a5565ad", GitCommit:"78c8293d1c65e8a153bf3c03802ab9358c0e1a14", GitTreeState:"clean", BuildDate:"2023-06-16T17:32:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
