### ISSUE TITLE
Selector "matchArgs" when used with either operator "Prefix" or "Postfix" doesn't work

### ISSUE THREAD

**Issue by vladimirkus** [cilium/tetragon#1355]
### What happened?

I'm trying to apply TracingPolicy in order to watch file reads and writes in some specific directory.
This is the example of a policy applied:
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-monitoring"
spec:
  kprobes:
  - call: "security_file_permission"
    syscall: false
    return: true
    args:
    - index: 0
      type: "file" # (struct file *) used for getting the path
    - index: 1
      type: "int" # 0x04 is MAY_READ, 0x02 is MAY_WRITE
    returnArg:
      index: 0
      type: "int"
    returnArgAction: "Post"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/etc/" # the files that we care
```
However, when configured either with "Prefix" or "Postfix" operator, it writes **all** filesystem events to `tetragon.log`, no matter the file path, meaning no filtering\selector is applied.
At the same time, when I used operator "Equal", example:
```
selectors:
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/etc/passwd" # the files that we care
      - index: 1
        operator: "Equal"
        values:
        - "2" # MAY_WRITE
        - "4" # MAY_READ
```
Selector works as expected and I saw only events with attempts accessing `/etc/passwd` in `process_kprobe.args{}.file_arg.path`

### Tetragon Version

0.10.0

### Kernel Version

OS: Ubuntu 20.04.6 LTS   
Kern: 5.15.60
Container-runtime: containerd://1.6.21

### Kubernetes Version

```Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.16", GitCommit:"51e33fadff13065ae5518db94e84598293965939", GitTreeState:"clean", BuildDate:"2023-07-19T12:19:24Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}```

### Bugtool

``tetra bugtool
Error: unknown command "bugtool" for "tetra"
Run 'tetra --help' for usage.``

### Relevant log output

```shell
I don't have any logs relevant for the issue
```

**Comment by vladimirkus** [comment]
Tried with another function: 
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: fd-install
spec:
  kprobes:
  - args:
    - index: 0
      returnCopy: false
      type: int
    - index: 1
      returnCopy: false
      type: file
    call: fd_install
    return: false
    selectors:
    - matchArgs:
      - index: 1
        operator: Prefix
        values:
        - /etc/
    syscall: false
```
the selector also didn't have any effect
