### ISSUE TITLE
Unable to use any operator except "Equal", "NotEqual", "Prefix", "Postfix" in "matchArgs" selector

### ISSUE THREAD

**Issue by vladimirkus** [cilium/tetragon#1394]
### What happened?

I'm trying to apply a TracingPolicy that will trace socket events only for any specific destination ports. According to the [doc](https://github.com/cilium/tetragon/blob/main/docs/content/en/docs/concepts/tracing-policy/selectors.md#operator-types) there are various operator types supported for the "matchArgs" selector that can help me to do it. However, each time I get the next error: 
```The TracingPolicy "tetragon-network-telemetry" is invalid: spec.kprobes[0].selectors[0].matchArgs[0].operator: Unsupported value: "DPort": supported values: "Equal", "NotEqual", "Prefix", "Postfix"```
Here is a policy example:
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "tetragon-network-telemetry"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
     - index: 0
       type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "DPort"
        values:
        - "9919"
  - call: "tcp_close"
    syscall: false
    args:
     - index: 0
       type: "sock"
```
What is the reason it's prohibited to use the "DPort" operator here? It seems like the "sock" struct has all the required data available: [doc](https://elixir.bootlin.com/linux/v5.15.60/source/include/net/sock.h#L374)
Is it a bug? Or probably I'm just missing something here. 

### Tetragon Version

0.10.0

### Kernel Version

OS: Ubuntu 20.04.6 LTS
Kern: 5.15.60
Container-runtime: containerd://1.6.21

### Kubernetes Version

```Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.16", GitCommit:"51e33fadff13065ae5518db94e84598293965939", GitTreeState:"clean", BuildDate:"2023-07-19T12:19:24Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}```

### Relevant log output

```shell
TracingPolicy "tetragon-network-telemetry" is invalid: spec.kprobes[0].selectors[0].matchArgs[0].operator: Unsupported value: "DPort": supported values: "Equal", "NotEqual", "Prefix", "Postfix"
```

**Comment by vladimirkus** [comment]
possibly a duplication of https://github.com/cilium/tetragon/issues/1081

**Comment by vladimirkus** [comment]
According to the [release notes](https://github.com/cilium/tetragon/releases/tag/v0.10.0) is should be available in v0.10
https://github.com/cilium/tetragon/pull/1008

**Comment by kevsecurity** [comment]
Hello @vladimirkus 👋  Can you supply the command you are using to apply the tracing policy please? Thanks

**Comment by kevsecurity** [comment]
Also @vladimirkus was this a new install or an upgrade? Just trying to gather everything we need to reproduce.

**Comment by vladimirkus** [comment]
Hello @kevsecurity,
1. It was upgrade from v0.9.0
2. I apply it with a command `kubectl apply -f tcp-connect-test.yaml --validate=false`, however, I have the same result trying to `kubectl edit` an existing policy as well as deploying policies using a custom helm chart.

**Comment by kevsecurity** [comment]
I think this is related to the operator not picking up the latest schema changes due to a version number error. A fix should avoid this in the future. For now. can you try a fresh install or upgrade to latest CI image and see if that fixes it?

For clarity, the operators are in 0.10 but if the operator hasn't upgraded the schema from 0.9 (or earlier) then it will only permit those operator types in k8s validation.

**Comment by vladimirkus** [comment]
I see, thank you for clarifying. Let me try this.

**Comment by vladimirkus** [comment]
- Upgrading to the CI build didn't have any effect on the issue, seems like the CRDs were not updated
- Uninstalling tetragon also didn't help 
- Removing `tracingpolicies*` CRDs alongside with reinstalling tetragon solved the issue

**Comment by kkourt** [comment]
Thanks for the report!
https://github.com/cilium/tetragon/pull/1409, which is included in the latest 0,11 release, should solve the issue.

So, updating from 0.10 to 0.11 should also update the CRD without the need to manually delete it.
I'm close it the issue, but feel free to reopen it if things do not work as expected.

Thanks again!

**Comment by vladimirkus** [comment]
Great, thank you!
Looking forward to seeing the new release :)

**Comment by vladimirkus** [comment]
Great, thank you!
I'm checking the new release.

**Comment by vladimirkus** [comment]
After upgrading from 0.10 to 0.11 the issue still exists.
So I had to remove the CRDs manually in order to overcome it.

**Comment by vladimirkus** [comment]
Additional question, after fixing the CRDs I'm trying to apply policy that uses the policy:
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: test
  namespace: test
spec:
  kprobes:
  - args:
    - index: 0
      type: sock
    call: tcp_connect
    selectors:
    - matchArgs:
      - index: 0
        operator: NotDPort
        values:
        - "9910"
        - "9911"
    syscall: false
  - args:
    - index: 0
      type: sock
    call: tcp_close
    selectors:
    - matchArgs:
      - index: 0
        operator: NotDPort
        values:
        - "9910"
        - "9911"
    syscall: false
```
However, I get the next error:
```
* spec.kprobes[0].selectors[0].matchArgs[0].operator: Unsupported value: "NotDPort": supported values: "Equal", "NotEqual", "Prefix", "Postfix", "GreaterThan", "LessThan", "GT", "LT", "SPort", "DPort", "SAddr", "DAddr", "Protocol", "Mask"
* spec.kprobes[1].selectors[0].matchArgs[0].operator: Unsupported value: "NotDPort": supported values: "Equal", "NotEqual", "Prefix", "Postfix", "GreaterThan", "LessThan", "GT", "LT", "SPort", "DPort", "SAddr", "DAddr", "Protocol", "Mask"
```

Are `Not` operators still not available in this release? Is it planned to add them to the next one?
