### ISSUE TITLE
kprobe can't override security_ functions

### ISSUE THREAD

**Issue by olsajiri** [cilium/tetragon#1441]
### What happened?

Paul Kim reported, that tetragon can't override 'security_*' functions (spec below) and we get following override attach error in logs:

```
time="2023-09-05T16:16:35Z" level=info msg="Added generic kprobe sensor: /var/lib/tetragon/bpf_generic_kprobe_v53.o -> security_file_permission" flags=none override=true
[...]
time="2023-09-05T16:16:42Z" level=warning msg="Failed to attach override program: %!w(*fmt.wrapError=&{attaching 'generic_kprobe_override' failed: setting perf event bpf program: invalid argument 0xc0002872c0})"
```

spec:
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-monitoring-filtered"
spec:
  kprobes:
  - call: "security_file_permission"
    syscall: false
    return: true
    args:
    - index: 0
      type: "file" # (struct file *) used for getting the path
    - index: 1
      type: "int" # 0x04 is MAY_READ, 0x02 is MAY_WRITE
    returnArg:
      index: 0
      type: "int"
    returnArgAction: "Post"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/etc/passwd" # the files that we care
      - index: 1
        operator: "Equal"
        values:
        - "2" # MAY_WRITE
      matchActions:
      - action: Override
        argError: -1
```

### Tetragon Version

0.11.0

### Kernel Version

5.7+
