### ISSUE TITLE
fieldfilters don't support underscore but some native fields have them

### ISSUE THREAD

**Issue by miloaissatu** [cilium/tetragon#1445]
### What happened?

Using Tetragon v0.10.0 deployed via helm on Rancher RKE2 v1.26.7+rke2r1 Kubernetes cluster and RockyLinux 8.6 OS kernel
Add a tracing policy for some kprobe unlink/truncate sys_calls
Add a field filter to include fields of interest / exclude fields to be dropped
```
  fieldFilters: |
    {"fields": "parent", "action": "EXCLUDE"}
    {"fields": "process", "action": "INCLUDE"}
    {"fields": "function_name", "action": "INCLUDE"}
    {"fields": "process.pod.docker", "action": "EXCLUDE"}
    {"fields": "process.pod.container.id", "action": "EXCLUDE"}
    {"fields": "process.pod.container.pid", "action": "EXCLUDE"}
    {"fields": "process.pod.container.image.id", "action": "EXCLUDE"}
```
Get validation errors on fields containing underscore.

Would be good if either the validations can be relaxed (not sure, haven't checked protobuf spec) or otherwise rename fields to be protobuf.FieldMask.paths compliant.

### Tetragon Version

v0.10.0

### Kernel Version

Rocky Linux release 8.6 (Green Obsidian) 4.18.0-372.32.1.el8_6.x86_64

### Kubernetes Version

Rancher RKE2 v1.26.7+rke2r1

### Relevant log output

```shell
# Tetragon operator/pod log emits this error
time="2023-09-08T09:42:06Z" level=fatal msg="Failed to start tetragon" error="proto: (line 1:45): google.protobuf.FieldMask.paths contains invalid path: \"function_name\""
```

### Anything else?

tracing policy
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sys-truncates-deletes"
spec:
  kprobes:
  - call: "sys_unlinkat"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "string"
    - index: 2
      type: "int"
  - call: "sys_renameat2"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "string"
    - index: 2
      type: "int"
    - index: 3
      type: "string"
    - index: 4
      type: "int"
  - call: "sys_ftruncate"
    syscall: true
    args:
    - index: 0
      type: "string"
    - index: 1
      type: "int"
  - call: "sys_truncate"
    syscall: true
    args:
    - index: 0
      type: "string"
    - index: 1
      type: "int"
```
example output without field filters
```
{
	"process_kprobe": {
		"process": {
			"exec_id": "c3k0cmFudzEwNTozNDAyODc0NTU3NTgzMDI6MzIxMTY5NA==",
			"pid": 3211694,
			"uid": 1000,
			"cwd": "/home/jovyan",
			"binary": "/usr/bin/rm",
			"arguments": "--coreutils-prog-shebang=rm /usr/bin/rm -rf /home/jovyan/shares",
			"flags": "execve clone",
			"start_time": "2023-09-08T09:12:57.693681692Z",
			"auid": 4294967295,
			"pod": {
				"namespace": "default",
				"name": "test",
				"container": {
					"id": "containerd://3191b34afc07b2305efd8ad972a16839d6cfe70f02caf1d41fba663094683b07",
					"name": "jupyter",
					"image": {
						"id": "registry/jupyter/main@sha256:667c29bd4470f00c24725d9c288a15b4271477149958e560ed2d65a12fbe5e8d",
						"name": "registry/jupyter/main:5.1.6-py3.11"
					},
					"start_time": "2023-09-08T05:29:09Z",
					"pid": 211
				},
				"pod_labels": {
					"app": "jupyterhub"
				}
			},
			"docker": "3191b34afc07b2305efd8ad972a1683",
			"parent_exec_id": "c3k0cmFudzEwNTozMzM3ODk3MzAwMDAwMDA6MzExNjQxNA==",
			"refcnt": 1,
			"tid": 3211694
		},
		"parent": {
			"exec_id": "c3k0cmFudzEwNTozMzM3ODk3MzAwMDAwMDA6MzExNjQxNA==",
			"pid": 3116414,
			"uid": 1000,
			"cwd": "/home/jovyan",
			"binary": "/usr/bin/bash",
			"flags": "procFS auid",
			"start_time": "2023-09-08T07:24:39.967923319Z",
			"auid": 4294967295,
			"pod": {
				"namespace": "default",
				"name": "test",
				"container": {
					"id": "containerd://3191b34afc07b2305efd8ad972a16839d6cfe70f02caf1d41fba663094683b07",
					"name": "jupyter",
					"image": {
						"id": "registry/jupyter/main@sha256:667c29bd4470f00c24725d9c288a15b4271477149958e560ed2d65a12fbe5e8d",
						"name": "registry/jupyter/main:5.1.6-py3.11"
					},
					"start_time": "2023-09-08T05:29:09Z",
					"pid": 93
				}
			},
			"docker": "3191b34afc07b2305efd8ad972a1683",
			"parent_exec_id": "c3k0cmFudzEwNTozMjY4NTg3MjAwMDAwMDA6MzAxNDA3Nw==",
			"refcnt": 2,
			"tid": 3116414
		},
		"function_name": "__x64_sys_unlinkat",
		"args": [{
			"int_arg": 5
		}, {
			"string_arg": "t1.txt"
		}, {
			"int_arg": 0
		}],
		"action": "KPROBE_ACTION_POST"
	},
	"node_name": "test",
	"time": "2023-09-08T09:12:57.695163347Z"
}
```
