### ISSUE TITLE
Specifying `return: true` without `returnArg: type:` causes a segfault.

### ISSUE THREAD

**Issue by cpaplham** [cilium/tetragon#1490]
### What happened?

Specifying `return: true` without providing a type for that return value causes a segfault (captured by the go runtime as a panic), which contains no information that obviously identifies that as the reason for the segfault.

Can be replicated with the following policy:
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "test"
spec:
  kprobes:
  - call: "security_file_permission"
    syscall: false
    return: true
    args:
    - index: 0
      type: "file"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
          - "/etc/passwd"

```

### Tetragon Version

v0.12.0-pre.0-66-g6785a3b1

### Kernel Version

5.15.0-83-generic

### Relevant log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a3dcf0]

goroutine 67 [running]:
github.com/cilium/tetragon/pkg/sensors/tracing.addKprobe({0x400229fe18, 0x18}, 0x4002410d20, 0x4000813b68)
        /home/cpaplham/tetragon/pkg/sensors/tracing/generickprobe.go:596 +0x530
github.com/cilium/tetragon/pkg/sensors/tracing.createGenericKprobeSensor({0x4000f62010, 0xc}, {0x4002410d20, 0x1, 0x1?}, 0x0?, {0x4002421da0?, 0x6?}, {0x0, 0x0, ...})
        /home/cpaplham/tetragon/pkg/sensors/tracing/generickprobe.go:487 +0x4ac
github.com/cilium/tetragon/pkg/sensors/tracing.policyHandler.PolicyHandler({}, {0x252ff00, 0x4002407380}, 0x813ca8?)
        /home/cpaplham/tetragon/pkg/sensors/tracing/policyhandler.go:38 +0x16c
github.com/cilium/tetragon/pkg/sensors.sensorsFromPolicyHandlers({0x252ff00, 0x4002407380}, 0x2407380?)
        /home/cpaplham/tetragon/pkg/sensors/handler.go:242 +0xd4
github.com/cilium/tetragon/pkg/sensors.(*handler).addTracingPolicy(0x40001b4500, 0x400240bfc0)
        /home/cpaplham/tetragon/pkg/sensors/handler.go:110 +0xd0
github.com/cilium/tetragon/pkg/sensors.startSensorManager.func1()
        /home/cpaplham/tetragon/pkg/sensors/manager.go:75 +0x138
created by github.com/cilium/tetragon/pkg/sensors.startSensorManager in goroutine 1
        /home/cpaplham/tetragon/pkg/sensors/manager.go:60 +0xc8
```
