### ISSUE TITLE
NotIn / In in matchBinaries does not work for binaries that were started before Tetragon

### ISSUE THREAD

**Issue by DimanNe** [cilium/tetragon#1535]
### What happened?

[Discussion thread on slack](https://cilium.slack.com/archives/C03EV7KJPJ9/p1695927719089099).

It looks like the current implementation of `matchBinaries` (see `int match_binaries` and `event_find_curr`) does not work for processes **that were started before Tetragon** (and including Tetragon itself).

This is a quick repro (assuming tetragon writes events in a log file), the intent of the policy below is to omit Tetragon's accesses to files:

```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-monitoring"
spec:
  kprobes:

  - call: "security_file_permission"
    syscall: false
    return: true
    returnArg: {index: 0, type: "int"}
    args:
    - { index: 0, type: "file"} # (struct file *) used for getting the path
    - { index: 1, type: "int" } # 0x04 is MAY_READ, 0x02 is MAY_WRITE
    selectors:
      - matchBinaries:
        - { operator: "NotIn", values: ["/usr/local/bin/tetragon"] }
```

This is what is observed:

```
tetra --server-address unix:///var/run/tetragon/tetragon.sock getevents -o compact
📝 write    /usr/local/bin/tetragon /var/log/tetragon/tetragon.log        
📝 write    /usr/local/bin/tetragon /var/log/tetragon/tetragon.log        
📝 write    /usr/local/bin/tetragon /var/log/tetragon/tetragon.log
```

### Tetragon Version

0.11.0

### Kernel Version

`Linux impedance 6.5.0-5-generic #5-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep  6 15:11:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

-----------------

cc @mtardy @jrfastab 

P.S.

It looks like there is a [potential rework of matchBinaries](https://github.com/cilium/tetragon/issues/1278#issuecomment-1721050905), so I am not sure if I really can help, but if I can — please let me know.
