### ISSUE TITLE
add PostUrl action

### ISSUE THREAD

**Issue by Oneiroi** [cilium/tetragon#1540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature you would like

Arming tetragon with the ability to send data as part of the GetUrl action would enable this to leverage slack webhooks and others.

e.g. a curl example for calling a webhook would be:

```
matchActions:
- action: PostUrl
   argUrl: https://hooks.slack.com/...
   argData: '{"channel":"C123456","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"Hi I am a bot that can post *_fancy_* messages to any public channel."}}]}'
   argAuth: "xoxb-not-a-real-token-this-will-not-work"
```

Full documentation is here for slack webhooks: https://api.slack.com/tutorials/tracks/posting-messages-with-curl 

*Caveat* doing so _could_ arguably suggest Tetragon itself could be used to Exfiltrate data, and certainly this _could_ be the case

Besides Slack webhooks this could also lend itself to supporting AWS Lambda (and other) calls for any existing automation (https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway-tutorial.html#services-apigateway-tutorial-invoke-function)

### Describe your proposed solution

addition of PostUrl action type;
argAuth should be optional and when supplied sends the header `Authorization: bearer ${argAuth}`
argJson should be inspected for valid JSON and send as bosy data in a POST request

potential future improvements: adding a  `argContentType` to allow for changes in the content type specified to send as a header in the POST rquest,

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
