### ISSUE TITLE
Applied rateLimit doesn't work well for file policies (e.g., security_file_permission)

### ISSUE THREAD

**Issue by vladimirkus** [cilium/tetragon#1918]
### What happened?

Applied rateLimit according to the [documentation](https://tetragon.io/docs/concepts/tracing-policy/selectors/#rate-limiting). Here is the whole tracing policy:

```
spec:
  kprobes:
  - args:
    - index: 0
      type: file
    - index: 1
      type: int
    call: security_file_permission
    return: true
    returnArg:
      index: 0
      maxData: false
      returnCopy: false
      type: int
    selectors:
    - matchActions:
      - action: Post
        rateLimit: 1m
      matchArgs:
      - index: 0
        operator: Prefix
        values:
        - /etc/passwd
      - index: 1
        operator: Equal
        values:
        - "4"
    syscall: false
```

As far as I understood from the documentation this may significantly decrease count of repetitive events, however this didn't have any noticeable effect.

During the experiment I generated events with ```while true; do cat /etc/passwd > /dev/null; done```.

Are there any constraints using rate limiting, or probably I misunderstood the concept?

### Tetragon Version

1.0.1

### Kernel Version

5.15

### Kubernetes Version

1.24
