### ISSUE TITLE
feature: filter: add selectors to filter auid (login uid) and rest of credentials 

### ISSUE THREAD

**Issue by tixxdz** [cilium/tetragon#1943]
Filtering by the auid (login uid) could be useful as in most daemon and services it is set to the invalid UID -1  unsigned 4294967295.  https://linux.die.net/man/8/pam_loginuid

Filtering by [process credentials](https://tetragon.io/docs/reference/grpc-api/#processcredentials) is also helpful.

Reference: https://cilium.slack.com/archives/C03EV7KJPJ9/p1704500286846389?thread_ts=1704210424.442369&cid=C03EV7KJPJ9

Solution should be something like:

- [ ] `matchLoginUid`
- [ ] `matchCredentials`: multiple fields of credentials where most of them are unsigned integer matching operation.

```
- matcgLoginUid:
  - operator: "NotEqual"
    values:
    - 4294967295  # exclude daemons
```

```
- matchCredentials:
  - Uid
    operator: "Equal"
    values:
    - 0
    - 1
  - Gid
    operator: "gt"
    values:
    - 1000
```

Will this cover all possible combinations? somehow long format, but that's currently how I see it... feel free to propose better solution.
