### ISSUE TITLE
Extract path from linux_binprm in security_bprm_check

### ISSUE THREAD

**Issue by dwindsor** [cilium/tetragon#1983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature you would like

With respect to [TOCTOU](https://cwe.mitre.org/data/definitions/367.html) issues, the most atomic way to block execution of a file is via the LSM hook `security_bprm_check`. This function is executed immediately before the kernel launches a new program, during its search for a handler for the format of the file being executed.

In order to write a `TracingPolicy` using the path provided to `security_bprm_check`, we need to add support to Tetragon for extracting the path from `struct linux_binprm`, the only argument to `security_bprm_check`.

# Testing

The following new `process_kprobe` was generated by running `sample-exec` with the following TracingPolicy:

```bash
dave@dev:~$ /usr/bin/sample-exec
* Before executing /usr/bin/id
/usr/bin/sample-exec: 4: /usr/bin/id: Operation not permitted
* After executing /usr/bin/id
```

## New `process_kprobe` for `security_bprm_check` events

```json
{
  "process_kprobe": {
    "process": {
      "exec_id": "OjI3ODc0MDQ4Mzc3NTczMjoxMDAxODc5",
      "pid": 1001879,
      "uid": 1000,
      "cwd": "/home/dave",
      "binary": "/usr/bin/sample-exec",
      "arguments": "/usr/bin/sample-exec",
      "flags": "execve",
      "start_time": "2024-01-11T23:27:18.871818530Z",
      "auid": 1000,
      "parent_exec_id": "OjI3ODc0MDQ4MzIwMjM0OToxMDAxODc4",
      "refcnt": 1,
      "tid": 1001879
    },
    "parent": {
      "exec_id": "OjI3ODc0MDQ4MzIwMjM0OToxMDAxODc4",
      "pid": 1001878,
      "uid": 1000,
      "cwd": "/home/dave",
      "binary": "/usr/bin/sample-exec",
      "arguments": "/usr/bin/sample-exec",
      "flags": "execve clone",
      "start_time": "2024-01-11T23:27:18.871244532Z",
      "auid": 1000,
      "parent_exec_id": "OjI3NTY3MDM5MDAwMDAwMDo5ODU1MzI=",
      "tid": 1001878
    },
    "function_name": "security_bprm_check",
    "args": [
      {
        "linux_binprm_arg": {
          "path": "/usr/bin/id"
        }
      }
    ],
    "action": "KPROBE_ACTION_OVERRIDE",
    "policy_name": "sample-no-exec-id",
    "return_action": "KPROBE_ACTION_POST"
  },
  "time": "2024-01-11T23:27:18.871925631Z"
}
```

## TracingPolicy
```yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sample-no-exec-id"
spec:
  kprobes:
  - call: "security_bprm_check"
    syscall: false
    args:
    - index: 0
      type: "linux_binprm"
    selectors:
      - matchBinaries:
        - operator: "In"
          values:
            - "/usr/bin/sample-exec"
        matchArgs:
          - index: 0
            operator: "Equal"
            values:
              - "/usr/bin/id"
        matchActions:
        - action: Override
          argError: -1
```

## `sample-exec`

```bash
#!/bin/sh

echo "* Before executing /usr/bin/id"
/usr/bin/id
echo "* After executing /usr/bin/id"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
