### ISSUE TITLE
Tetragon pod stuck in pending Defaulted container "export-stdout" out of: export-stdout, tetragon

### ISSUE THREAD

**Issue by carloshdezbueno** [cilium/tetragon#2130]
### What happened?

[cilium-sysdump-20240221-164921.zip](https://github.com/cilium/tetragon/files/14361805/cilium-sysdump-20240221-164921.zip)

### Tetragon Version

v1.0.2 and v1.0.1

### Kernel Version

Its running in k8s

### Kubernetes Version

Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-gke.1575000

### Bugtool

cilium sysdump

### Relevant log output

```shell
Defaulted container "export-stdout" out of: export-stdout, tetragon
```

**Comment by kkourt** [comment]
Thanks for the report, it seems that some of the tetragon pods were not scheduled:
```
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-02-21T13:02:37Z"
      message: '0/6 nodes are available: 1 Too many pods. preemption: 0/6 nodes are
        available: 6 No preemption victims found for incoming pod.'
      reason: Unschedulable
      status: "False"
      type: PodScheduled
    phase: Pending
    qosClass: Burstable
```
