### ISSUE TITLE
Add a new type argTypeDev to support device-based filter

### ISSUE THREAD

**Issue by sfc-gh-gshe** [cilium/tetragon#2165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Yes. 

I want to leverage the tracepoint net_dev_start_xmit to monitor the per-device TX traffic. Given that, I hope to filter the traffic by device name to avoid large amount of un-related traffic like lo devices.

With such feature, we may be able to achieve the similar functionality of tcpdump.

### Describe the feature you would like

With such feature, we may further be able to achieve the similar functionality of tcpdump fitlering by devices.

### Describe your proposed solution

I find that we already have argTypeSkb and argTypeSock for filtering. So I am thinking about if we can add argTypeDev for `struct net_device`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevsecurity** [comment]
#2196 adds minimal support for the struct net_device * type.

**Comment by kevsecurity** [comment]
#2196 has been merged. You can use a kprobe policy like this to see it in action (use latest CI image):
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "dev-hard-start-xmit"
spec:
  kprobes:
  - call: "dev_hard_start_xmit"
    syscall: false
    args:
    - index: 1
      type: "net_device"
    selectors:
    - matchArgs:
      - index: 1
        operator: Equal
        values:
        - "lo"
```

or if you do want to use a tracepoint, then you could use a tracepoint policy like this instead (based on a recent addition, again use latest CI image):
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "net-dev-start-xmit"
spec:
  tracepoints:
  - subsystem: "net"
    event: "net_dev_start_xmit"
    args:
    - index: 4
      type: "data_loc"
    - index: 6
      type: "skb"
    selectors:
    - matchArgs:
      - index: 4
        operator: Equal
        values:
        - "lo"
```
