### ISSUE TITLE
TracingPolicies do not get applied in WSL2

### ISSUE THREAD

**Issue by joshuajorel** [cilium/tetragon#2338]
### What happened?

I am building the `main` branch from my local WSL2 environment and `TracingPolicy` and `TracingPolicyNamespaced` do not get applied. I am running the following example:

```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "fd-install"
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "file"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/tmp/tetragon"
      matchActions:
      - action: Sigkill
``` 

### Tetragon Version

Tetragon build from [1dee96d7d58b7ccc57e955eb71b4c1e72f87293d ](https://github.com/cilium/tetragon/commit/1dee96d7d58b7ccc57e955eb71b4c1e72f87293d)

### Kernel Version

Linux DESKTOP-KI004JQ 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2

### Bugtool

[tetragon-bugtool.tar.gz](https://github.com/cilium/tetragon/files/14996961/tetragon-bugtool.tar.gz)

### Anything else?

Only `process_events` get captured and no other event gets captured.
