### ISSUE TITLE
gRPC server can't be disabled

### ISSUE THREAD

**Issue by lambdanis** [cilium/tetragon#2477]
Tetragon Helm chart exposes an option to disable the gRPC server, but it doesn't work. With the following Helm values:
```yaml
tetragon:
  grpc:
    enabled: false
```
the gRPC server is started on `localhost:54321`. In this case the server address isn't specified in the configmap, but the flag [defaults to](https://github.com/cilium/tetragon/blob/4c47837a06f473b45ad189149c63853f2f502304/pkg/option/flags.go#L288) localhost:54321.

Moreover, when I set the grpc server address to an empty string:
```yaml
tetragon:
  grpc:
    address: ""
```
the gRPC server started on `:54321`. This behaviour seems to be introduced by #896 which fixed a backwards incompatibility introduced by #552.

What I'd expect is that both of these configs disable the gRPC server.
