### ISSUE TITLE
Not able to use rateLimit on tcp_connect calls

### ISSUE THREAD

**Issue by vladimirkus** [cilium/tetragon#2486]
### What happened?

I'm trying to use rateLimit on tpc_connect calls, example:
```
spec:
  kprobes:
  - args:
    - index: 0
      maxData: false
      returnCopy: false
      type: sock
    call: tcp_connect
    return: false
    selectors:
    - matchActions:
      - action: Post
        rateLimit: 1m
        rateLimitScope: process
      matchArgs:
      - index: 0
        operator: NotDPort
        values:
        - "9910"
        - "9911"
    syscall: false
```

I wrote a small python program that opens and closes sockets:
```
import socket
import time

# Function to open and close a TCP socket in an infinite loop for a set duration
def open_and_close_socket(host, port, duration):
    start_time = time.time()
    while time.time() - start_time < duration:
        try:
            # Create a socket object
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                # Connect to the given host and port
                s.connect((host, port))
                print(f"Connected to {host}:{port}")

        except Exception as e:
            print(f"An error occurred: {e}")

        finally:
            # Close the socket
            s.close()
            print(f"Disconnected from {host}:{port}")

        # Short delay to prevent overwhelming the server or network
        time.sleep(0.1)

# Replace 'example.com' with the target host and '80' with the target port
host = '93.184.215.14'
port = 80
duration = 120  # Duration set for 2 minutes

open_and_close_socket(host, port, duration)
```

And when I run it, I observed that rateLimit didn't really drop events.
I checked events' args:
```
process_kprobe: { 
     action: KPROBE_ACTION_POST
     args: [ 
       { 
         sock_arg: {
           cookie: 18446621494401152128
           daddr: 93.184.215.14
           dport: 80
           family: AF_INET
           protocol: IPPROTO_TCP
           saddr: ***
           sport: 36720
           state: TCP_SYN_SENT
           type: SOCK_STREAM
         }
       }
     ]
```

And I noticed that source port is probably the thing here, as it's chosen randomly per each opened socket. 

Question: is there any way of using rateLimit on tcp_connect? Probably fieldFilter might help?

### Tetragon Version

v1.1.0

### Kernel Version

5.15.60

### Kubernetes Version

v1.24.16
