### ISSUE TITLE
Add an ID field to the detection rule to help trace it back to the TracingPolicy

### ISSUE THREAD

**Issue by alex-ilgayev** [cilium/tetragon#259]
At the moment, all tracing events received from tetragon don't have any context to the "TracingPolicy" defined that rule in the first place.
For kprobe events for example, the best chance to correlate it is by using the `function_name` field, which may have several policy hooks for that specific function, so it isn't sufficient.

A sample usage could be to trace several kinds of write operations to files, that each belongs to a different kind of policy, and analyze the output properly depending on the source policy.
Many more use cases could be thought of.

That ID field could be the `metadata.name` for tracing policy which is usually defined:

```yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "fd_install"
...
```
