### ISSUE TITLE
Support Postfix operator in matchBinaries selector

### ISSUE THREAD

**Issue by anfedotoff** [cilium/tetragon#2679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Sometimes you know only binary name and this binary can be in different folders on different machines. In operator is limited by elements count.

### Describe the feature you would like

Selector can look like:

```yaml
- matchBinaries:
      - operator: "Postfix"
        values:
        - "qemu-system-x86_64"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
