### ISSUE TITLE
Cannot extract path from struct task_struct

### ISSUE THREAD

**Issue by dwindsor** [cilium/tetragon#2742]
The LSM hook to interpose access decisions on signal delivery is:

```c
int security_task_kill(struct task_struct *p, struct kernel_siginfo *info, int sig, const struct cred *cred);
```

It would be useful to be able to write policy that allows denial of signal delivery to a certain process. To that end, the first parameter of `security_task_kill` is the `struct task_struct` representing the target process to which the signal `sig` will be delivered.

While we can easily extract `pid` from `struct task_struct`, it would also be useful to be able to extract the path to which the `struct task_struct` is pointing. We should opportunistically extract the path - not all `task_struct` instances will have backing binaries.

OTOH I think the best way to get at the path is `struct task_struct->nameidata`, which contains `struct path` members `path` and `root`, which can be passed to `d_path_local`.

**Comment by Shireenbanu** [comment]
Hi @mtardy,

This appears to be already implemented, as I tested with the policy below:

```yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: protect-sshd-from-kill
spec:
  lsmhooks:
  - hook: task_kill
    args:
    - index: 0
      type: path
      resolve: "mm.exe_file.f_path"
    - index: 2
      type: int
    selectors:
    - matchArgs:
      - index: 0
        operator: Equal
        values:
        - "/usr/sbin/sshd"
      - index: 2
        operator: Equal
        values:
        - "9"
      matchActions:
      - action: Override
        argError: -1
```
I think this was enabled by the resolve field added for bprm_check_security-style path, and it seems to work the same way for task_kill. Let me know if there's anything left to do here that I could help with.
