### ISSUE TITLE
The returnArg of TracingPolicy does not work as documented

### ISSUE THREAD

**Issue by z63d** [cilium/tetragon#3369]
### What happened?

The document describes the following TracingPolicy. However, when I apply this, an error occurs.
https://tetragon.io/docs/concepts/tracing-policy/hooks/#return-values

```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sample"
spec:
  kprobes:
  - call: "sk_alloc"
    syscall: false
    return: true
    args:
    - index: 1
      type: int
      label: "family"
    returnArg:
      type: sock
```

```
❯ kubectl apply -f sample-tracing-policy.yaml
The TracingPolicy "sample" is invalid: spec.kprobes[0].returnArg.index: Required value
```

Checking the [TracingPolicy CRD](https://github.com/cilium/tetragon/blob/v1.3.0/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml#L221-L304), the following format seems to be correct:

```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sample"
spec:
  kprobes:
  - call: "sk_alloc"
    syscall: false
    return: true
    args:
    - index: 1
      type: int
      label: "family"
    returnArg:
      index: 0
      type: sock
```

```
❯ kubectl apply -f sample-tracing-policy.yaml
tracingpolicy.cilium.io/sample created
```

Is this the expected behavior?
If this is a mistake in the documentation, I will fix it.

### Tetragon Version

1.3.0

### Kernel Version

6.12.10-orbstack-00297-gf8f6e015b993

### Kubernetes Version

1.32.0

### Relevant log output

```shell

```
