### ISSUE TITLE
Q: uprobes in cluster

### ISSUE THREAD

**Issue by n-bes** [cilium/tetragon#3572]
Hi.

I'm a little confused working with uprobes tracing policy.

## python scenarion
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "python3-uprobe"
spec:
  uprobes:
  - path: "/usr/bin/python3"
    symbols:
      - "PyObject_ASCII"
      - "PyObject_AsCharBuffer"
```

In my case, it is crashed because `/usr/bin/python3` not exists. Also I mentioned that it is compiles some bpf program against binary while applying the policy. 

* Could describe, how it works?
* What if multiply binaries exists? (Pythoninv 3.11 / 3.12)
* Does this require a running application? Compiles against all binaries matched by name?

## bash scenarion 
I'm back to example from docs: https://tetragon.io/docs/concepts/tracing-policy/hooks/#uprobes. 
I added all available functions (~1k). It works but required a lot of time (~30 min) for preparing. Could it be faster?
