### ISSUE TITLE
Problem with IPv6 addresses in `NotDAddr` operator

### ISSUE THREAD

**Issue by kobrineli** [cilium/tetragon#3639]
### What happened?

Hi!
I'm trying to create TracingPolicy for tcp-accept events with filtering of destination addressed, and I have some problems with IPv6 addresses in NotDAddr  operator.
Consider we have policy like this:

```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "tcp-accept"
spec:
  options:
  - name: "disable-kprobe-multi"
    value: "1"
  kprobes:
  - call: "sk_alloc"
    syscall: false
    return: true
    args:
    - index: 1
      type: int
      label: "Family"
    returnArg:
      index: 0
      type: sock
    returnArgAction: TrackSock
    selectors:
    - matchBinaries:
      - operator: "Prefix"
        followChildren: false
        values:
        - "/home/kobrineli/accept"
      matchActions:
      - action: NoPost
  - call: "sk_free"
    syscall: false
    args:
    - index: 0
      type: sock
    selectors:
    - matchActions:
      - action: UntrackSock
        argSock: 0
      matchActions:
      - action: NoPost
      matchBinaries:
      - operator: "Prefix"
        followChildren: false
        values:
        - "/home/kobrineli/accept"

  - call: "tcp_set_state"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchBinaries:
      - operator: "Prefix"
        followChildren: false
        values:
        - "/home/kobrineli/accept"
      matchArgs:
      - index: 0
        operator: "State"
        values:
        - "TCP_ESTABLISHED"
```

Here is an example of reported event:

```
{
  "process_kprobe": {
    "process": {
      "exec_id": "bWFkYXJhOjIyNjY5NDYyNjE1NDcyNjoyNDg2MDQ0",
      "pid": 2486044,
      "uid": 1001,
      "cwd": "/home/kobrineli",
      "binary": "/home/kobrineli/accept4",
      "flags": "execve clone",
      "start_time": "2025-04-15T10:51:17.754617373Z",
      "auid": 1001,
      "parent_exec_id": "bWFkYXJhOjcxMDUzMDE2MDAwMDAwMDoxOTkzNzEy",
      "refcnt": 1,
      "tid": 2486044,
      "in_init_tree": false
    },
    "parent": {
      "exec_id": "bWFkYXJhOjcxMDUzMDE2MDAwMDAwMDoxOTkzNzEy",
      "pid": 1993712,
      "uid": 1001,
      "cwd": "/home/kobrineli",
      "binary": "/usr/bin/zsh",
      "flags": "procFS auid",
      "start_time": "2025-04-11T15:21:44.579054362Z",
      "auid": 1001,
      "parent_exec_id": "bWFkYXJhOjUzNzkyMzg1MDAwMDAwMDoxMzI4OTg5",
      "tid": 1993712,
      "in_init_tree": false
    },
    "function_name": "tcp_set_state",
    "args": [
      {
        "sock_arg": {
          "family": "AF_INET",
          "type": "SOCK_STREAM",
          "protocol": "IPPROTO_TCP",
          "saddr": "127.0.0.1",
          "daddr": "127.0.0.1",
          "sport": 1234,
          "dport": 34686,
          "cookie": "18446616172714246336",
          "state": "TCP_ESTABLISHED"
        }
      }
    ],
    "action": "KPROBE_ACTION_POST",
    "policy_name": "tcp-accept",
    "return_action": "KPROBE_ACTION_POST"
  },
  "node_name": "madara",
  "time": "2025-04-15T10:51:19.125728787Z"
}
```

If I add filter on the destination address like this, everything woks fine, I still have event reports:
```
      - index: 0
        operator: "NotDAddr"
        values:
        - "127.0.0.3"
```

But if I add filter on the destination address, containing an IPv6 address in the list of values (e.g. ::3), I don't have any events, though the destination address is 127.0.0.1 :
```
      - index: 0
        operator: "NotDAddr"
        values:
        - "::3"
```

Are there any issues with IPv6 addresses in (Not)?(S|D)Addr  operators?

### Tetragon Version

v1.4.0

### Kernel Version

6.8.0-52-generic

### Relevant log output

```shell

```
