### ISSUE TITLE
kprobes policy with out of order arguments does not work as expected

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#3710]
Consider this policy:

```yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sys-lseek"
spec:
  kprobes:
  - call: "sys_lseek"
    syscall: true
    args:
    - index: 0
      type: "int"
      label: "index 0"
    - index: 1
      type: "int"
      label: "index 1"
    - index: 2
      type: "int"
      label: "index 2"
```

If we execute:
```
echo "0 1 2" | ./contrib/tester-progs/lseek-pipe
```

The args in the event we get are:
```json
[
  {
    "int_arg": 0,
    "label": "index 0"
  },
  {
    "int_arg": 1,
    "label": "index 1"
  },
  {
    "int_arg": 2,
    "label": "index 2"
  }
]
```

Consider the same policy but with the arguments reversed:
```yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sys-lseek"
spec:
  kprobes:
  - call: "sys_lseek"
    syscall: true
    args:
    - index: 2
      type: "int"
      label: "index 2"
    - index: 1
      type: "int"
      label: "index 1"
    - index: 0
      type: "int"
      label: "index 0"
```

We then get:
```json
[
  {
    "int_arg": 0,
    "label": "index 2"
  },
  {
    "int_arg": 1,
    "label": "index 1"
  },
  {
    "int_arg": 2,
    "label": "index 0"
  }
]
```

Which is not what we would expect.
