### ISSUE TITLE
NotDAddr filter error with `::ffff:127.0.0.1`

### ISSUE THREAD

**Issue by kobrineli** [cilium/tetragon#3712]
### What happened?

Hi! I've found a bug while filtering addresses for kprobe on `tcp_connect` function.
Consider we have tracing policy:

```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "tcp-connect"
spec:
  kprobes:
    - call: "tcp_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchArgs:
            - index: 0
              operator: "NotDAddr"
              values:
                - 127.0.0.1
                - ::1
                - ::ffff:127.0.0.1
```

which filters ipv4 loopback adress, ipv6 loopback address and ipv4 loopback address in ipv6 form.

Now let's listen for connections with `netcat`:

```
nc -l 1234
```

And connect to  opened local port also with `netcat`:

```
nc ::ffff:127.0.0.1 1234
```

Despite filters on destination address, tetragon still generates event:
```
{
  "process_kprobe": {
    "process": {
      "exec_id": "bWluaWt1YmU6MzQwODY2MDY3MzU4MzQ4OjMwNjUwNDA=",
      "pid": 3065040,
      "uid": 1001,
      "cwd": "/home/kobrineli",
      "binary": "/usr/bin/nc",
      "arguments": "::ffff:127.0.0.1 1234",
      "flags": "execve clone",
      "start_time": "2025-05-07T12:11:58.495582072Z",
      "auid": 1001,
      "parent_exec_id": "bWluaWt1YmU6MzM5NDY4NTI4MjU1NTEwOjMwNDc0NTM=",
      "refcnt": 1,
      "cap": {},
      "tid": 3065040,
      "in_init_tree": false
    },
    "function_name": "tcp_connect",
    "args": [
      {
        "sock_arg": {
          "family": "AF_INET6",
          "type": "SOCK_STREAM",
          "protocol": "IPPROTO_TCP",
          "saddr": "127.0.0.1",
          "daddr": "127.0.0.1",
          "sport": 43318,
          "dport": 1234,
          "cookie": "18446638556892972544",
          "state": "TCP_SYN_SENT"
        }
      }
    ],
    "action": "KPROBE_ACTION_POST",
    "policy_name": "tcp-connect",
    "return_action": "KPROBE_ACTION_POST"
  },
  "node_name": "minikube",
  "time": "2025-05-07T12:11:58.498154577Z"
}
```

Seems like tetragon doesn't support such form of address.

### Tetragon Version

v1.4.0

### Kernel Version

6.8.0-52-generic

### Relevant log output

```shell

```
