### ISSUE TITLE
matchArgs: NotDAddr filter unexpectedly drops valid events on tcp_sendmsg

### ISSUE THREAD

**Issue by erolg** [cilium/tetragon#3715]
### What happened?

When using `matchArgs` with `operator: NotDAddr` in a `tcp_sendmsg` kprobe, events that **should match** are being silently dropped — even though the destination IP clearly does *not* fall within the excluded ranges.

This behavior does not occur when the `matchArgs` selector is removed.

**Policy:**
```yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: connect
spec:
  kprobes:
    - call: tcp_sendmsg
      syscall: false
      args:
        - index: 0
          type: sock
      selectors:
        - matchArgs:
            - index: 0
              operator: NotDAddr
              values:
                - 10.232.0.0/14
                - 127.0.0.0/8
                - 169.0.0.0/8


Dropped example event:

📤 sendmsg project-x/app-8bd55445f-9l54x /usr/bin/java tcp 10.233.67.2:56604 -> 10.117.98.45:11210 bytes 0

### Tetragon Version

1.4.0

### Kernel Version

5.15.0-117-generic

### Kubernetes Version

v1.20.7

### Bugtool

_No response_

### Relevant log output

```shell

```

**Comment by erolg** [comment]
I can also get events but some of them drops. Could it be selector's side effect? Because tcp_sendmsg produce lots of events.

**Comment by erolg** [comment]
I'm trying to monitor dropped but valid TCP events, so I removed the selector section from the following TracingPolicy:


```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
  name: connect
spec:
  kprobes:
    - call: tcp_sendmsg
      syscall: false
      return: false
      args:
        - index: 0
          type: sock
```

However, once I remove the matchArgs section, I start seeing Tetragon's own TCP events, even though I’ve configured both export-allowlist and export-denylist as follows:


```
export-allowlist: '{"event_set":["PROCESS_KPROBE"]}'
export-denylist: |-
  {"event_set": ["PROCESS_EXIT"]}
  {"health_check": true}
  {"namespace": ["", "cilium", "kube-system", "tetragon"]}
```
Yet I still see events like:

```
📤 sendmsg tetragon/tetragon-2xkhn /usr/bin/tetragon tcp 127.0.0.1:54321 -> 127.0.0.1:52400 bytes 0
🚀 process k8s-p-discovery-p2-25mars-worker-1 /usr/bin/runc ...
💥 exit    k8s-p-discovery-p2-25mars-worker-1 /usr/bin/runc ... 0
```

Shouldn't these events be suppressed by the export-denylist? Am I missing something, or is there an additional filter I should apply?
