### ISSUE TITLE
bpf: issue with resolve on the second argument.

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#3734]
Consider the following two policies

First:
```yaml
apiVersion: cilium.io/v2alpha1
kind: TracingPolicy
metadata:
  name: "capset"
  annotations:
    author: "Isovalent"
spec:
  kprobes:
    - call: "security_capset"
      syscall: false
      selectors:
      args:
        - index: 1
          type: "cap_effective"
          resolve: "cap_effective"
          label: "old_creds.cap_effective"
```

Second:
```yaml
apiVersion: cilium.io/v2alpha1
kind: TracingPolicy
metadata:
  name: "capset"
  annotations:
    author: "Isovalent"
spec:
  kprobes:
    - call: "security_capset"
      syscall: false
      selectors:
      args:
        - index: 0
          type: "cap_effective"
          resolve: "cap_effective"
          label: "new_creds.cap_effective"
        - index: 1
          type: "cap_effective"
          resolve: "cap_effective"
          label: "old_creds.cap_effective"
```

Executing sudo /bin/true gives different results.

First:
```json
    "args": [
      {
        "cap_effective_arg": "0000000000000002",
        "label": "old_creds.cap_effective"
      }
    ],
```

Second:
```json
    "args": [
      {
        "cap_effective_arg": "000001ffffffffff",
        "label": "new_creds.cap_effective"
      },
      {
        "cap_effective_arg": "000001ffffffffff",
        "label": "old_creds.cap_effective"
      }
    ],
```

AFAICT, the  correct answer is the one provided by he second policy.
