### ISSUE TITLE
URL and DNS entries will not work correctly if there are mutiple selectors.

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#476]
The tracing policy syntax has one action per selector. Currently, GetUrl and DnsRequest actions will work if any of the selectors match instead of working only when the specific selector that the action is defined in matches. This might lead to unexpected results when using multiple selectors.

**Comment by FedeDP** [comment]
Is this still relevant? In my local tests, the issue seems gone.

**Comment by mtardy** [comment]
> Is this still relevant? In my local tests, the issue seems gone.

Could you detail which TracingPolicy you tried to see how you combined the selectors? Might be possible that it was fixed and we could close this :)

**Comment by FedeDP** [comment]
Yup, this is the policy i tried:
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "test"
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: "file"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/home/fdipierr/test1"
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/home/fdipierr/test2"
      matchActions:
      - action: GetUrl
        argUrl: http://google.com  
```

I can only see the `geturl` action when i `cat test2`.
This is also visible from tetra output:
```
./tetra getevents -e PROCESS_KPROBE
{"process_kprobe":..,"binary":"/usr/bin/cat","arguments":"test1",...,"action":"KPROBE_ACTION_POST","policy_name":"test","return_action":"KPROBE_ACTION_POST"}...
{"process_kprobe":..,"binary":"/usr/bin/cat","arguments":"test2",...,"action":"KPROBE_ACTION_GETURL","policy_name":"test","return_action":"KPROBE_ACTION_POST"}...
```
