### ISSUE TITLE
what does this mean“ pid operator: NotIn”

### ISSUE THREAD

**Issue by sunnoy** [cilium/tetragon#516]
```yaml
    selectors:
    - matchPIDs:
    # Enum=In;NotIn
      - operator: NotIn

        followForks: true

        isNamespacePID: true 
        values:
        - 1
```
