### ISSUE TITLE
how to select sock args

### ISSUE THREAD

**Issue by sunnoy** [cilium/tetragon#526]
i  apply this 

```yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "connect"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
     - index: 0
       type: "sock"
    selectors:
    - matchArgs:
      - index: 0
      # Enum=Equal;NotEqual;Prefix;Postfix
        operator: "Equal"
        values:
        - '{"family": "AF_INET","type": "SOCK_STREAM"}'
```

got 
```
time="2022-11-03T06:53:42Z" level=warning msg="adding tracing policy failed" error="parseMatchArgs  error: writeMatchValues error: MatchArgs values {\"family\": \"AF_INET\",\"type\": \"SOCK_STREAM\"} unsupported"
```
thoungh code

```go
pkg/selectors/kernel.go
		case argTypeSock, argTypeSkb, argTypeCharIovec:
			return fmt.Errorf("MatchArgs values %s unsupported", v)
		}
```

so now unsupported ?
