### ISSUE TITLE
[Question]How to observe HTTP request events

### ISSUE THREAD

**Issue by Y-dc** [cilium/tetragon#533]
I want to observe network events like TCP,DNS,HTTP. Refer to crd example [tcp-connect](https://github.com/cilium/tetragon/blob/main/crds/examples/tcp-connect.yaml) , i got tcp,dns done, but I don't know how to observe HTTP events. Is there an example？Or any reference or suggestion?
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "tcp"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
     - index: 0
       type: "sock"
    selectors:
  - call: "tcp_close"
    syscall: false
    args:
     - index: 0
       type: "sock"
    selectors:
  - call: "tcp_sendmsg"
    syscall: false
    args:
     - index: 0
       type: "sock"
     - index: 2
       type: "int"
  - call: "tcp_recvmsg"
    syscall: false
    args:
      - index: 0
        type: "sock"
      - index: 2
        type: "int"
      - index: 4
        type: "int"

apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "dns"
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 1
      type: "file"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/etc/resolv.conf"
        - "/etc/hosts"
  - call: "udp_sendmsg"
    syscall: false
    args:
    - index: 0
      type: "sock"
  - call: "udp_recvmsg"
    syscall: false
    args:
    - index: 0
      type: "sock"
    - index: 2
      type: "size_t"
```
 i tried to observe socket kernel method like __sock_create, __sock_release, but it's difficult to distinguish HTTP request.

**Comment by Y-dc** [comment]
i tried tracepoint of syscalls, but the char_buf read cause the error "CharBufErrorPageFault", except for some stdout
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "syscalls"
spec:
  tracepoints:
    - subsystem: syscalls
      event: sys_enter_connect
      args:
        - index: 5
          type: "fd"
        - index: 7
          type: "int"
    - subsystem: syscalls
      event: sys_exit_connect
      args:
        - index: 5
          type: "int"
    - subsystem: syscalls
      event: sys_enter_accept
      args:
        - index: 5
          type: "fd"
    - subsystem: syscalls
      event: sys_exit_accept
      args:
        - index: 5
          type: "int"
    - subsystem: syscalls
      event: sys_enter_accept4
      args:
        - index: 5
          type: "fd"
        - index: 8
          type: "int"
    - subsystem: syscalls
      event: sys_exit_accept4
      args:
        - index: 5
          type: "int"
    - subsystem: syscalls
      event: sys_enter_close
      args:
        - index: 5
          type: "fd"
    - subsystem: syscalls
      event: sys_exit_close
      args:
        - index: 5
          type: "int"
    - subsystem: syscalls
      event: sys_enter_write
      args:
        - index: 5
          type: "fd"
        - index: 6
          type: "char_buf"
          sizeArgIndex: 7
        - index: 7
          type: "size_t"
    - subsystem: syscalls
      event: sys_exit_write
      args:
        - index: 5
          type: "int"
    - subsystem: syscalls
      event: sys_enter_read
      args:
        - index: 5
          type: "fd"
        - index: 6
          type: "char_buf"
          sizeArgIndex: 7
        - index: 7
          type: "size_t"
    - subsystem: syscalls
      event: sys_exit_read
      args:
        - index: 5
          type: "int"
    - subsystem: syscalls
      event: sys_enter_sendmsg
      args:
        - index: 5
          type: "fd"
        - index: 7
          type: "int"
    - subsystem: syscalls
      event: sys_exit_sendmsg
      args:
        - index: 5
          type: "int"
    - subsystem: syscalls
      event: sys_enter_recvmsg
      args:
        - index: 5
          type: "fd"
        - index: 7
          type: "int"
    - subsystem: syscalls
      event: sys_exit_recvmsg
      args:
        - index: 5
          type: "int"
```
i add some debug 
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/39187264/201932465-541e3803-5865-472e-9624-8ff1e0aaa1a2.png">
stdout:
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/39187264/201932758-1817404b-dff7-4e5b-9474-2a9412132810.png">

**Comment by Y-dc** [comment]
i got http metrics by this way.

1. tracepoints ```sys_enter_writer``` and ```sys_enter_read```
```
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "http"
spec:
  tracepoints:
    - subsystem: syscalls
      event: sys_enter_write
      args:
        - index: 5
          type: "fd"
        - index: 6
          type: "char_buf"
          sizeArgIndex: 8
        - index: 7
          type: "size_t"
    - subsystem: syscalls
      event: sys_enter_read
      args:
        - index: 5
          type: "fd"
        - index: 6
          type: "char_buf"
          sizeArgIndex: 8
        - index: 7
          type: "size_t"
```

2. parse http request/response message and get relevant information through golang net/http from char_buf args
```
func parseResponseMessage(value []byte, namespace, pod, binary string) {
	// try to parse the buf as http response
	resp, err := http.ReadResponse(bufio.NewReader(bytes.NewReader(value)), nil)
	if err != nil {
		//fmt.Printf("Failed to parse Response, %s\n", err)
		return
	}

	TracePointHttpResponse.WithLabelValues(namespace, pod, binary, strconv.Itoa(resp.StatusCode)).Inc()
}

func parseRequestMessage(value []byte, namespace, pod, binary string) {
	// try to parse the buf as http request
	req, err := http.ReadRequest(bufio.NewReader(bytes.NewReader(value)))
	if err != nil {
		//fmt.Printf("Failed to parse Request, %s\n", err)
		return
	}

	TracePointHttpRequest.WithLabelValues(
		namespace, pod, binary, req.Proto, req.Host, req.Method, req.RequestURI).Inc()
}
```

result :
<img width="1773" alt="image" src="https://user-images.githubusercontent.com/39187264/202950363-d2d0a6ed-db37-4a05-bb45-e15164d3c3d1.png">
