### ISSUE TITLE
network filters

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#702]
Tetragon already supports [sock](https://github.com/cilium/tetragon/blob/main/bpf/process/types/sock.h) and [skb](https://github.com/cilium/tetragon/blob/main/bpf/process/types/skb.h) types that can be used to extract information.

For example:
```
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
     - index: 0
       type: "sock"

```

And:

```
  kprobes:
  - call: "dev_queue_xmit"
    syscall: false
    args:
     - index: 0
       type: "skb"
```

We should also add filters (e.g., source/destination port/addr/CIDR) and be able to write policies for those.
