### ISSUE TITLE
Type `fd` makes kprobes tracing policy fail silently

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#893]
It seems that the `fd` type makes the following TracingPolicy not work and just outputs no events silently (without errors). If you just replaced the index 0 arg with `type: "int"`, it works.

Tested on:
- `Linux box 5.19.0-38-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 17:36:31 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`
- `Linux ip-172-31-17-70 5.15.0-1031-aws #35-Ubuntu SMP Fri Feb 10 02:07:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux` 

```yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-access"
spec:
  kprobes:
  - call: "sys_read"
    syscall: true
    args:
    - index: 0
      type: "fd"
    - index: 1
      type: "char_buf"
      returnCopy: true
    - index: 2
      type: "size_t"
    selectors:
    - matchBinaries:
      - operator: In
        values:
        - "/usr/bin/cat"
```
