### ISSUE TITLE
Add 'and' mask filter on argument

### ISSUE THREAD

**Issue by olsajiri** [cilium/tetragon#933]
When having filter on open/openat it'd be usefull to be able
to filter on flag value for specific mask like:

```
apiVersion: cilium.io/v1alpha1
metadata:
  name: "sys-openat"
spec:
  kprobes:
  - call: "sys_openat"
    return: false
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "string"
    - index: 2
      type: "int"
    returnArg:
      type: "int"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/tmp/passwd\0"
      - index: 2
        operator: "And"
        values:
          - 1  # O_WRONLY
          - 2  # O_RDWR
```

The matchArgs 'index: 2' filter would AND values on 3rd argument value and pass the filter if any of that  results != 0.
