### ISSUE TITLE
Add return value filter

### ISSUE THREAD

**Issue by olsajiri** [cilium/tetragon#934]
When having filter on open/openat it'd be usefull to be able
to filter on return value - file descriptor value, like:

```
apiVersion: cilium.io/v1alpha1
metadata:
  name: "sys-openat"
spec:
  kprobes:
  - call: "sys_openat"
    return: false
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "string"
    - index: 2
      type: "int"
    returnArg:
      type: "int"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/tmp/passwd\0"
      matchReturnArg:
      - operator: ">"
        values:
        - 0
```

The matchReturnArg would filter out events that do not have return value 'file descriptor' > 0.
